MvcApplication6/MvcApplication6/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using test1.Models;

namespace MvcApplication6.Controllers
{
    public class DriversController : Controller
    {
        private shipContext db = new shipContext();

        //
        // GET: /Drivers/

        public ActionResult Index()
        {
            return View(db.Drivers.ToList());
        }

        //
        // GET: /Drivers/Details/5

        public ActionResult Details(int id = 0)
        {
            Drivers drivers = db.Drivers.Find(id);
            if (drivers == null)
            {
                return HttpNotFound();
            }
            return View(drivers);
        }

        //
        // GET: /Drivers/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Drivers/Create

        [HttpPost]
        public ActionResult Create(Drivers drivers)
        {
            if (ModelState.IsValid)
            {
                db.Drivers.Add(drivers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drivers);
        }

        //
        // GET: /Drivers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Drivers drivers = db.Drivers.Find(id);
            if (drivers == null)
            {
                return HttpNotFound();
            }
            return View(drivers);
        }

        //
        // POST: /Drivers/Edit/5

        [HttpPost]
        public ActionResult Edit(Drivers drivers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drivers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drivers);
        }

        //
        // GET: /Drivers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Drivers drivers = db.Drivers.Find(id);
            if (drivers == null)
            {
                return HttpNotFound();
            }
            return View(drivers);
        }

        //
        // POST: /Drivers/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Drivers drivers = db.Drivers.Find(id);
            db.Drivers.Remove(drivers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication6/MvcApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/Scripts/HexCalcs.js")
        @Scripts.Render("~/Scripts/HexagonTools.js")
        @Scripts.Render("~/Scripts/Grid.js")
    </head>
    <body>
        <header>
            <div class="content-wrapper">

                <div class="float-right">

                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Draw", "Hex", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                            <li>@Html.ActionLink("Trucks", "Index", "Trucks")</li>
                            <li>@Html.ActionLink("Cargo", "Index", "Cargo")</li>
                            <li>@Html.ActionLink("Driver", "Index", "Drivers")</li>

                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>


        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>